vich_uploader:
    db_driver: orm

    mappings:
        avatar_profil:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
